app:
  routes:
    auth-service:
      uri: ${AUTH_SERVICE_URL:http://auth-service:8080}
    data-importer:
      uri: ${DATA_IMPORTER_URL:http://data-importer:8080}
    profile-service:
      uri: ${PROFILE_SERVICE_URL:http://profile-service:8080}
    project-service:
      uri: ${PROJECT_SERVICE_URL:http://project-service:8080}
    mentor-service:
      uri: ${MENTOR_SERVICE_URL:http://mentor-service:8080}
    job-market-analytics-service:
      uri: ${JOB_MARKET_ANALYTICS_SERVICE_URL:http://job-market-analytics-service:8080}

monitoring:
  prometheus:
    password: ${PROMETHEUS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

telegram-bot-adapter:
  auth:
    username: ${TELEGRAM_ADAPTER_USERNAME}
    password: ${TELEGRAM_ADAPTER_PASSWORD}
