spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: ${app.routes.auth-service.uri}
              predicates:
                - Path=/api/auth/**
            - id: data-importer
              uri: ${app.routes.data-importer.uri}
              predicates:
                - Path=/api/data-importer/**

app:
  http-client:
    connect-timeout: 2000
    read-timeout: 6000
  routes:
    auth-service:
      uri: ${AUTH_SERVICE_URI}
    data-importer:
      uri: ${DATA_IMPORTER_URI}
    profile-service:
      uri: ${PROFILE_SERVICE_URI}
    project-service:
      uri: ${PROJECT_SERVICE_URI}

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

monitoring:
  prometheus:
    password: ${PROMETHEUS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
