name: Trigger E2E Tests

on:
  pull_request:
    branches:
      - staging
      - dev
  workflow_dispatch:

jobs:
  trigger-e2e:
    name: Trigger E2E Test in e2e repo
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            FULL_SHA="${{ github.event.pull_request.head.sha }}"
          else
            FULL_SHA="${{ github.sha }}"
          fi
          echo "full_sha=$FULL_SHA" >> $GITHUB_OUTPUT
          echo "sha_short=$(echo $FULL_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Wait for all checks
        uses: step-security/wait-for-status-checks@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delay: 10s
          interval: 15s
          timeout: 300s

      - name: Trigger E2E workflow and wait for result
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: it-mentor-community-platform
          repo: e2e-tests
          github_token: '${{ secrets.E2E_TRIGGER_TOKEN }}'
          workflow_file_name: ci.yml
          ref: dev
          client-payload: |
            {
              "gateway_tag": "sha-${{ steps.vars.outputs.sha_short }}"
            }
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          wait_interval: 15
